# apollo 所需要的appid，每个微服务都要有！
app:
  id: 100005555
spring:
  application:
    name: xbrl-cloud‐config
server:
  port: 12000

apollo:
  bootstrap:
    enabled: true
    # 注入非默认application namespace或多个namespace的配置
    namespaces: application,SAMPLE.apollo
    ## 从1.2.0版本开始，如果希望把日志相关的配置（如logging.level.root=info或logback-spring.xml中的参数）也放在Apollo管理，那么可以额外配置apollo.bootstrap.eagerLoad.enabled=true来使Apollo的加载顺序放到日志系统加载之前，不过这会导致Apollo的启动过程无法通过日志的方式输出(因为执行Apollo加载的时候，日志系统压根没有准备好呢
    eagerLoad:
      enable: true
