# 公共配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  redis:
    database: 1
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 20
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true